# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d066b04437a7f06510dcf702abecc95dcaa0f265ac4503ec611244b5ca963c032c4326f6fcc94a0f80822857caf2b385d8762b2e08618c7652bbdff83a50e8ed

test:
  secret_key_base: 663e074b898c54079c8e02afc83f75f35084c954e2df92d4b49c53b56d1813e75fbdff5f45d52ee89e1ebc21ecfbd947a629a1d165d7b25b9f2acbd33a7eed2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mandrill_username: <%= ENV["MANDRILL_USERNAME"] %>
  mandrill_apikey: <%= ENV["MANDRILL_APIKEY"] %>
